Addressed TimJ comments
lsst-dm/dmtn-140 pull request #7
Opened 2020-09-22 23:58 UTC by gcomoretto

2020-09-24 22:06 UTC, leannep requested changes

2020-09-24 22:06 UTC, leannep commented on body.tex
>  This approach is not only used by DM, but also by other Rubin Observatory subsystems, that are facing the same challenge.
Rubin Observatory subsystems that are facing the same challenge.

2020-09-24 22:06 UTC, leannep commented on body.tex
> +The Rubin Observatory will perform in its first 10 years of observations the Legacy Survey of Space and Time, as described
In its first 10 years of observations Rubin Observatory will perform the Legacy Survey of Space and Time, as described in ....

2020-09-24 22:06 UTC, leannep commented on body.tex
> +software, services, and systems that will automatically reduce the raw data to produce science-ready data products.
and preparing the software, services, and systems

2020-09-24 22:29 UTC, timj commented on local.bib
> +       author = {{Ivezi{\'c}}, {\v{Z}}eljko and {Kahn}, Steven M. and
probably want this to be "FirstAuthor and others" to prevent lines and lines of names in the references.

2020-09-24 22:29 UTC, timj commented on body.tex
> +This material is based on work supported in part by the  {National Science Foundation} through Cooperative Agreement 1258333 managed by the  {Association of Universities for Research in Astronomy} (
There seems to be an extra space before "AURA".

2020-09-30 00:46 UTC, leannep approved these changes

2020-09-30 00:52 UTC, merged